server:
  port: 0
  servlet:
    context-path: /ad

spring:
  application:
    name: ad-service
  datasource:
    url: jdbc:mysql://localhost:3306/ad-db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true